# Generated by Django 4.0.6 on 2022-12-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userNumber',
        ),
    ]
